### ISSUE TITLE
Mute commands.

### ISSUE THREAD

**Issue by ghost** [Guardians-Stuff/Guardian#10]
I would like it if someone from the community worked on this.

Commands i need:
> mute, unmute, tempmute

**Comment by Simpleboy353** [comment]
I don't think thats needed. Discord already has timeouts.

**Comment by ghost** [comment]
Yeah but many people still use mute commands with a bot than timeout.

**Comment by mattizhu** [comment]
Your only options is to create a role called "Muted" and attach it to the user when using the mute command, or loop through every accessable channel and forum post and append the user with their `SEND_MESSAGES` and `ADD_REACTIONS` permission revoked.

**Comment by ghost** [comment]
Oki.... I'll let someone else work on this if anyone wants to help.
